version: '2'
services:
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - web-variables.env
  magento:
    image: 'quadpaymagento'
    env_file:
      - web-variables.env
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
volumes:
  db-data:
    driver: local
