version: '2'
services:
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - web-variables.env
  magento:
    image: 'favicode-quadpay'
    env_file:
      - web-variables.env
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - db
      - redis
  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
    container_name: phpmyadmin
volumes:
  db-data:
    driver: local
  redis-data:
    driver: local