#!/usr/bin/env bash

su favicode <<EOSU

/var/www/html/bin/magento setup:install --backend-frontname=$MAGENTO_BACKEND_FRONTNAME \
--db-host=$MYSQL_HOST --db-name=$MAGENTO_DATABASE_NAME \
--db-user=$MAGENTO_DATABASE_USER --db-password=$MAGENTO_DATABASE_PASSWORD \
--base-url=$MAGENTO_BASE_URL --admin-user=$MAGENTO_ADMIN_USERNAME \
--admin-password=$MAGENTO_ADMIN_PASSWORD --admin-email=$MAGENTO_ADMIN_EMAIL \
--admin-firstname=$MAGENTO_ADMIN_FIRSTNAME --admin-lastname=$MAGENTO_ADMIN_LASTNAME \
--use-rewrites 1 --session-save=redis --session-save-redis-host=redis --session-save-redis-db=1 --language=en_US --currency=USD --timezone=America/Chicago \
--cache-backend=redis \
--cache-backend-redis-server=redis \
--cache-backend-redis-db=2 \
--page-cache=redis \
--page-cache-redis-server=redis \
--page-cache-redis-db=3


EOSU