#!/usr/bin/env bash

su favicode <<EOSU

ln -s ~/.composer/auth.json /var/www/html/var/composer_home/

/var/www/html/bin/magento sampledata:deploy

/var/www/html/bin/magento setup:upgrade

/var/www/html/bin/magento deploy:mode:set production

EOSU